Repository DataDog/jmeter-datadog-backend-listener, pull requests merged in 2021-04, with the labels that each got.

#10 Add screenshot
  README.md
  images/screenshot.png
Labels: changelog/no-changelog, documentation

#8 Update license
  LICENSE-3rdparty.csv
  src/main/java/org/datadog/jmeter/plugins/DatadogConfiguration.java
  src/main/java/org/datadog/jmeter/plugins/aggregation/DatadogSketch.java
  src/main/java/org/datadog/jmeter/plugins/exceptions/DatadogApiException.java
  src/main/java/org/datadog/jmeter/plugins/exceptions/DatadogConfigurationException.java
  src/test/java/org/datadog/jmeter/plugins/DatadogConfigurationTest.java
  src/test/java/org/datadog/jmeter/plugins/aggregation/DatadogSketchTest.java
Labels: changelog/no-changelog

#9 Create CODEOWNERS
  .github/CODEOWNERS
Labels: changelog/no-changelog

#11 Update junit to 4.13.1
  pom.xml
Labels: changelog/no-changelog, dev/testing

#12 Update version in pom.xml to 0.1.1-SNAPSHOT
  pom.xml
Labels: changelog/no-changelog
